apiVersion: v1
kind: Secret
metadata:
  name: app-kubenews-secret
type: Opaque
stringData:
  ## postgres
  POSTGRES_USER: "kubenews" 
  POSTGRES_PASSWORD: "kubenews@"
  POSTGRES_DB: "kubenews"   
  ## kubenews
  DB_DATABASE: "kubenews"
  DB_HOST: "postgres-kube-news"
  DB_USERNAME: "kubenews"
  DB_PASSWORD: "kubenews@"
