apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-config
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-configuracao
  template:
    metadata:
      labels:
        app: app-configuracao
    spec:
      containers:
        - name: app-config
          image: kubedevio/app-variaveis-ambiente:v1
          ports:
            - containerPort: 3000
          env:
            - name: APP_NAME #variavel da aplicacao
              valueFrom:
                configMapKeyRef:
                  name: app-config #nome do configMap
                  key: AAPP_NAME #variavel dentro do configMap
            - name: APP_VERSION
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AAPP_VERSION
            - name: APP_AUTHOR
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AAPP_AUTHOR               
---
apiVersion: v1
kind: Service
metadata:
  name: app-config
spec:
  selector:
    app: app-configuracao
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      name: http
      protocol: TCP
      nodePort: 30000
